### ISSUE TITLE
Some tests are broken

### ISSUE THREAD

**Issue by let4be** [http-tests/cache-tests#115]
Hello!
Awesome project

I'm currently trying to test a custom reverse-proxy cache, but some tests fail due to the fact that request forwarded to the cache test server returns with 5xx

For example:
```
npm run cli --base=http://localhost:9999/ --id=stale-close-s-maxage=2

> http-cache-tests@0.4.5 cli
> node --no-warnings test-engine/cli.mjs

Running stale-close-s-maxage=2
=== Client request 1
    GET http://localhost:9999//test/cc394f86-feba-426e-a0a1-2887d8860ae4
    Pragma: foo
    Cache-Control: nothing-to-see-here
    Test-Name: Shared HTTP cache must not serve stale stored response when prohibited by `Cache-Control: s-maxage`
    Test-ID: stale-close-s-maxage=2
    Req-Num: 1

=== Client response 1
    HTTP 200 OK
    cache-control: max-age=2, s-maxage=2
    capability-seen: 
    client-request-count: 1
    connection: close
    content-length: 36
    content-type: text/plain
    date: Fri, 25 Aug 2023 07:51:58 GMT
    request-numbers: 1
    server-base-url: /test/cc394f86-feba-426e-a0a1-2887d8860ae4
    server-now: 1692949918170
    server-request-count: 1

=== Client request 2
    GET http://localhost:9999//test/cc394f86-feba-426e-a0a1-2887d8860ae4
    Pragma: foo
    Cache-Control: nothing-to-see-here
    Test-Name: Shared HTTP cache must not serve stale stored response when prohibited by `Cache-Control: s-maxage`
    Test-ID: stale-close-s-maxage=2
    Req-Num: 2

=== Client response 2
    HTTP 502 Bad Gateway
    connection: close
    content-length: 0
    date: Fri, 25 Aug 2023 07:52:01 GMT

==== Results
⛔️ - Response 2 comes from cache
```

logs for the test cache server:
```
=== Server response 1
    HTTP 200 OK
    server-base-url: /test/cc394f86-feba-426e-a0a1-2887d8860ae4
    server-request-count: 1
    client-request-count: 1
    server-now: 1692949918170
    capability-seen: 
    cache-control: max-age=2, s-maxage=2
    content-type: text/plain
    request-numbers: 1

=== Server request 2
    GET /test/cc394f86-feba-426e-a0a1-2887d8860ae4
    host: localhost:9999
    user-agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
    accept: */*
    accept-encoding: gzip,deflate
    cache-control: nothing-to-see-here
    pragma: foo
    req-num: 2
    test-id: stale-close-s-maxage=2
    test-name: Shared HTTP cache must not serve stale stored response when prohibited by `Cache-Control: s-maxage`
    x-forwarded-for: 127.0.0.1

=== Server response 2
    [ server disconnect ]

=== Server request 3
    GET /test/cc394f86-feba-426e-a0a1-2887d8860ae4
    host: localhost:9999
    user-agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
    accept: */*
    accept-encoding: gzip,deflate
    cache-control: nothing-to-see-here
    pragma: foo
    req-num: 2
    test-id: stale-close-s-maxage=2
    test-name: Shared HTTP cache must not serve stale stored response when prohibited by `Cache-Control: s-maxage`
    x-forwarded-for: 127.0.0.1

=== Server response 3
    [ server disconnect ]
```

Reverse proxy itself is fine, but it forwards the request to the server run by `cache-tests` and this server returns `502 Bad Gateway`

Any idea what's up? This is not the only test with such error
